[project]
name = 'Decentralized-Government-Regulatory-Sandbox'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.innovation-registration]
path = 'contracts/innovation-registration.clar'
clarity_version = 2
epoch = 2.5

[contracts.outcome-measurement]
path = 'contracts/outcome-measurement.clar'
clarity_version = 2
epoch = 2.5

[contracts.regulatory-waver]
path = 'contracts/regulatory-waver.clar'
clarity_version = 2
epoch = 2.5

[contracts.testing-boundary]
path = 'contracts/testing-boundary.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
